# Generated by Django 2.2.19 on 2023-10-06 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_auto_20231005_0841"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CounterIngredient",
            new_name="IngredientInRecipe",
        ),
    ]
